console.log("l  l  l")
console.log("l  l  l")
console.log("l  l  l")
console.log("l  l  l")
console.log("l__l__l")
console.log("l  l  l")
console.log("l  l  l")
console.log("l  l  l")
console.log("l  l  l")
console.log("l  l  l")
console.log("l  l  l")
console.log("l  l  l")
console.log("l  l  l")
console.log("l  I  l")

